### ISSUE TITLE
add name to build factory steps

### ISSUE THREAD

**Issue by aliceinwire** [gentoo/Gentoo_kernelCI#35]

**Comment by mjeveritt** [comment]
@aliceinwire : you can assign this one to me, if you like .. its WIP currently, will push soon™ 😉

**Comment by aliceinwire** [comment]
@mjeveritt any progress on this ?

**Comment by aliceinwire** [comment]
fixed by https://github.com/gentoo/Gentoo_kernelCI/pull/53/commits/5d606cc6eab6b1dd8e8e850426941cdc0959ec45
