### ISSUE TITLE
DNS Resolution failure results in false negative (build marked as failed)

### ISSUE THREAD

**Issue by kuzetsa** [gentoo/Gentoo_kernelCI#36]
Upon failure to resolve github.com the CI bot seems to have prematurely marked the build as a failure, and not retried the fetch or performed a build test.

References:

1. [recent ck-sources build test by Gentoo_kernelCI bot](http://kernel1.amd64.dev.gentoo.org:8010/#/builders/16/builds/137)
2. [new commit, showing same DNS-type error as above](http://kernel1.amd64.dev.gentoo.org:8010/#/builders/16/builds/141)

**Comment by aliceinwire** [comment]
removed the deprecated kernelci2 worker.
now looks working again with the kernelci worker.
unfortunately, there is no easy way to rebuild job built on kernelci2 with kernelci.
