### ISSUE TITLE
qemu: could not load kernel '/boot/vmlinuz-sys-kernel/ck-sources/ck-sources-4.13.13': No such file or directory

### ISSUE THREAD

**Issue by aliceinwire** [gentoo/Gentoo_kernelCI#37]
WARNING: Image format was not specified for '/tmp/gentoo.qcow2' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
qemu: could not load kernel '/boot/vmlinuz-sys-kernel/ck-sources/ck-sources-4.13.13': No such file or directory
vmimage present: /tmp/gentoo.qcow2

**Comment by kuzetsa** [comment]
when was this fixed? either way: closing the bug.

issue hasn't returned in several months / still working as-of today.
