### ISSUE TITLE
gentoo qcow2 image is locked and cannot be used at same time

### ISSUE THREAD

**Issue by aliceinwire** [gentoo/Gentoo_kernelCI#48]
qemu-system-x86_64: -hda /tmp/gentoo.qcow2: Failed to get "write" lock
Is another process using the image?

http://kernel1.amd64.dev.gentoo.org:8010/#/builders/3/builds/49/steps/13/logs/stdio

**Comment by mjeveritt** [comment]
Ah, there should be ways around this, and a second worker is one 🙂
