### ISSUE TITLE
add cross build enviroment in kernel2

### ISSUE THREAD

**Issue by aliceinwire** [gentoo/Gentoo_kernelCI#59]
we need to install 
armv7a-hardfloat-linux-gnueabi-gcc 
in kernel2.amd64.dev.gentoo.org

**Comment by mjeveritt** [comment]
@aliceinwire can I get access to kernel2?

If so, I will set up crossdev and build an arm toolchain or two, and we can get some testing going ..

I have armv7, armv6 (old R-Pi) and aarch64 hardware available .. although perhaps we can ask whether it would be better to use the packet.net box for aarch64 and do the building natively - what do you think? Leio is point-of-contact for that if/when we want to try it.

**Comment by mjeveritt** [comment]
> @aliceinwire can I get access to kernel2?
>
> If so, I will set up crossdev and build an arm toolchain or two, and we can get some testing going ..

I have been corrected on this .. will set the process in motion later this evening (2018-07-12).

**Comment by aliceinwire** [comment]
As now I'm trying to use the following command but without success:
crossdev -S -t armv7a-hardfloat-linux-gnueabi-gcc

**Comment by aliceinwire** [comment]
from binutils logs, there is something wrong in the configuration process
can you investigate?

**Comment by aliceinwire** [comment]
https://paste.pound-python.org/show/aD9Lcn8cTioAbJmYSuZP/

**Comment by kuzetsa** [comment]
I just ran two commands to investigate:

```
emerge --ask app-portage/gentoolkit
eshowkw sys-devel/crossdev 
```

the amd64 keyword-stabilized sys-devel/crossdev-20171230 is the installed version.

locally (*not on kernel2*) I'll try to test with newer crossdev before doing anything else.

**Comment by kuzetsa** [comment]
I didn't notice at first, but I think -gcc isn't  
considered by crossdev part of a  tuple:

```
crossdev -S -t armv7a-hardfloat-linux-gnueabi
```

^ in progress (*"on rails" / automatic: I'll monitor until crossdev has finished*)

**Comment by kuzetsa** [comment]
```
$ armv7a-hardfloat-linux-gnueabi-gcc --version && \
which armv7a-hardfloat-linux-gnueabi-gcc

armv7a-hardfloat-linux-gnueabi-gcc (Gentoo Hardened 6.4.0-r1 p1.3) 6.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

/usr/bin/armv7a-hardfloat-linux-gnueabi-gcc
```

I think issue #59 can be closed now.

**Comment by kuzetsa** [comment]
footnote:

... changing to armv7a-hardfloat-linux-newlib  
(*instead of armv7a-hardfloat-linux-gnueabi*)

would still be a valid cross-toolchain for testing the kernel,  
but it would be less of a gentoo-specific test to use that libc  
(*because glibc is the usual libc in gentoo "stable" profiles*)

I think it's probably best to stick with gnueabi if it's for stabilization,  
but newlibc (*or musl*) can test embedded-type support.

the footprint of a glibc-based static-linked busybox payload
was about one megabyte (*smaller than the kernel itself*)

```
  File: armpayload-initramfs.gz
  Size: 1049413   	Blocks: 2056       IO Block: 4096   regular file
```
