### ISSUE TITLE
kernel2 update to cross-armv7a-hardfloat-linux-gnueabi/gcc-7.3.0-r3

### ISSUE THREAD

**Issue by kuzetsa** [gentoo/Gentoo_kernelCI#64]
gcc 7.3 is now keyword stabilized for arm architecture.

After I've finished testing (*locally*) I'd like to bump this crossdev target on

```
kernel2.amd64.dev.gentoo.org
```

(*which is still on gcc-6.4.0-r1*)

I don't see any reason to run CI / QA for older version of toolchain components than the latest keyword-stabilized version.

I have time in the next few days to perform the bump, but if anyone's if anyone's workflow will be disrupted by this change, please let me know before thursday (*July 26th*).

**Comment by aliceinwire** [comment]
thanks ! :+1:

**Comment by kuzetsa** [comment]
python 3.6 is stable-keyworded now too,
and buildbot has an update, etc.
(*not touching those: it wasn't discussed*)

**Comment by kuzetsa** [comment]
```
Calculating dependencies... done!
>>> Calculating removal order...
 cross-armv7a-hardfloat-linux-gnueabi/gcc
    selected: 6.4.0-r1 
   protected: none 
     omitted: 7.3.0-r3 

[...]

removed 'armv7a-hardfloat-linux-gnueabi-g++-6.4.0'
removed 'armv7a-hardfloat-linux-gnueabi-gcc-6.4.0'

kernel2 ~ # gcc-config --list-profiles
 [1] armv7a-hardfloat-linux-gnueabi-7.3.0 *
 [2] x86_64-pc-linux-gnu-7.3.0 *
```

---

(*cross-armv7a-hardfloat-linux-gnueabi/gcc bumped*)
